!function() {
    var Consts = {
        UNCOMPRESSED: 0,
        DEFLATE: 1,
        LZMA: 2,
        AWD_FIELD_INT8: 1,
        AWD_FIELD_INT16: 2,
        AWD_FIELD_INT32: 3,
        AWD_FIELD_UINT8: 4,
        AWD_FIELD_UINT16: 5,
        AWD_FIELD_UINT32: 6,
        AWD_FIELD_FLOAT32: 7,
        AWD_FIELD_FLOAT64: 8,
        AWD_FIELD_BOOL: 21,
        AWD_FIELD_COLOR: 22,
        AWD_FIELD_BADDR: 23,
        AWD_FIELD_STRING: 31,
        AWD_FIELD_BYTEARRAY: 32,
        AWD_FIELD_VECTOR2x1: 41,
        AWD_FIELD_VECTOR3x1: 42,
        AWD_FIELD_VECTOR4x1: 43,
        AWD_FIELD_MTX3x2: 44,
        AWD_FIELD_MTX3x3: 45,
        AWD_FIELD_MTX4x3: 46,
        AWD_FIELD_MTX4x4: 47,
        INT8: 1,
        INT16: 2,
        INT32: 3,
        UINT8: 4,
        UINT16: 5,
        UINT32: 6,
        FLOAT32: 7,
        FLOAT64: 8,
        AWDSTRING: 31,
        AWDBYTEARRAY: 32,
        MAGIC: 4282180,
        GENERIC: 0,
        GEOMETRY: 1,
        PRIMITIVE: 11,
        CONTAINER: 22,
        MESH: 23,
        MATERIAL: 81,
        TEXTURE: 82,
        SKELETON: 101,
        SKELETON_POSE: 102,
        SKELETON_ANIMATION: 103,
        ANIMATION_SET: 113,
        ANIMATOR: 122,
        NAMESPACE: 254,
        METADATA: 255,
        MODEL_ENTITY: 2,
        MODEL_SKYBOX: 4,
        MODEL_CAMERA: 8,
        MODEL_SEGMENT_SET: 16,
        MODEL_MESH: 32,
        MODEL_GEOMETRY: 64,
        MODEL_SKELETON: 128,
        MODEL_SKELETON_POSE: 256,
        MODEL_CONTAINER: 512,
        MODEL_TEXTURE: 1024,
        MODEL_TEXTURE_PROJECTOR: 2048,
        MODEL_MATERIAL: 4096,
        MODEL_ANIMATION_SET: 8192,
        MODEL_ANIMATION_STATE: 16384,
        MODEL_ANIMATION_NODE: 32768,
        MODEL_ANIMATOR: 65536,
        MODEL_STATE_TRANSITION: 1 << 17,
        MODEL_LIGHT: 1 << 18,
        MODEL_LIGHT_PICKER: 1 << 19,
        MODEL_SHADOW_MAP_METHOD: 1 << 20,
        MODEL_EFFECTS_METHOD: 1 << 21,
        MODEL_GENERIC: -1,
        POSITION: 1,
        INDEX: 2,
        UVS: 3,
        NORMAL: 4,
        TANGENT: 5,
        JOIN_IDX: 6,
        JOIN_WGT: 7,
        SUVS: 8,
        COLOR: 11,
        BINORMAL: 12,
        DEFAULT_NS: 0
    };
    module.exports = Consts;
}();